import sqlalchemy as sa
from sqlalchemy.ext.mutable import MutableDict

from main_def.models.base_class import Base, TimestampMixin


class DataSourceFormatMaster(Base):
    __tablename__ = "DataSourceFormatMaster"
    format_id = sa.Column("FormatID", sa.String(32), primary_key=True)
    name = sa.Column("Name", sa.String(256), nullable=False)
    priority = sa.Column("Priority", sa.SmallInteger, nullable=False, default=9999)
    ext = sa.Column("Ext", MutableDict.as_mutable(sa.JSON))

    FORMAT_ID_MP4_FULL = "74BA994CF2B54C40946EA62C3979DDA3"
    FORMAT_ID_MP4_STATIC = "C78F687CB3BE4D90B30F49435317C3AC"
    FORMAT_ID_MP4_LIVE = "7F8B6CD82F28437888BD029EFDA1E57F"
    FORMAT_ID_MP4_COVER = "F5D2FE4A15FB405E988A7309FD3F9920"
    FORMAT_ID_MP4_FEATURE = "408EEAB1D3CF41F3941F62F97372184F"
    FORMAT_ID_MP4_REMIX = "BB423826E6FA4839BBB4DA718F483D18"
    FORMAT_ID_MP4_LYRIC = "3CF047F3B0F349B3A9A39CE7FDAB1DA6"

    FORMAT_ID_MP3_FULL = "1A67A5F1E0D84FB9B48234AE65086375"
    FORMAT_ID_MP3_LIVE = "745BFC108F41441CB01AD8178AB02D2B"
    FORMAT_ID_MP3_FEATURE = "87ADA22693BA48029C33FC3031C6044C"
    FORMAT_ID_MP3_COVER = "C417CF7DC12C4A21A0B3576871823156"

    FORMAT_ID_MP4_FAN_CAM = "DDC08421CAEB4E918F3FE373209020F9"

    FORMAT_ID_MP4_UNPLUGGED = "AA65FCC828C44DDBB4643774C7FC2CDC"
    FORMAT_ID_MP4_MASHUP = "EC894B72A75F4EEF8AC826F9C738E718"
    FORMAT_ID_MP4_DANCE = "53F98DD107264900880230A93B7C7D3C"
    FORMAT_ID_MP4_TOUR = "9811A1D5025C4CC1A2617F33C5CE2D44"
    FORMAT_ID_MP4_360_VR = "DE642D1D589E4756BCEDD00F3F4739D7"
    FORMAT_ID_MP4_INSTRUMENTAL = "32743C22DE7C4588A50999E59D6D1240"
    FORMAT_ID_MP4_KARAOKE = "6E2FFC37CD1C49F8B1A30431F2046F59"
    FORMAT_ID_MP4_INTERVIEW = "635BEC3F66774782B84550735B96E175"
    FORMAT_ID_MP4_BACKSTAGE = "F3B8FA91FF4F49DB8D3FD3D24D376EBA"
    FORMAT_ID_MP4_TV_SPOT = "A9DCA88904C94794A04B31579F6CE2FD"
    FORMAT_ID_MP4_TUTORIAL = "B438AE36342B40778BF6997486A56918"
    FORMAT_ID_MP4_USER_COLLECT = ""

    FORMAT_IDS_DATASOURCE_FEATURE = [FORMAT_ID_MP4_FEATURE, FORMAT_ID_MP3_FEATURE]
    FORMAT_IDS_DATASOURCE_REMIX = [FORMAT_ID_MP4_REMIX]
    FORMAT_IDS_DATASOURCE_LYRIC = [FORMAT_ID_MP4_LYRIC]
    FORMAT_IDS_DATASOURCE_LIVE = [FORMAT_ID_MP4_LIVE, FORMAT_ID_MP3_LIVE]
    FORMAT_IDS_DATASOURCE_COVER = [FORMAT_ID_MP4_COVER, FORMAT_ID_MP3_COVER]
    FORMAT_IDS_DATASOURCE_FAN_CAM = [FORMAT_ID_MP4_FAN_CAM]

    FORMAT_IDS_DATASOURCE_UNPLUGGED = [FORMAT_ID_MP4_UNPLUGGED]
    FORMAT_IDS_DATASOURCE_MASHUP = [FORMAT_ID_MP4_MASHUP]
    FORMAT_IDS_DATASOURCE_DANCE = [FORMAT_ID_MP4_DANCE]
    FORMAT_IDS_DATASOURCE_TOUR = [FORMAT_ID_MP4_TOUR]
    FORMAT_IDS_DATASOURCE_360_VR = [FORMAT_ID_MP4_360_VR]
    FORMAT_IDS_DATASOURCE_INSTRUMENTAL = [FORMAT_ID_MP4_INSTRUMENTAL]
    FORMAT_IDS_DATASOURCE_KARAOKE = [FORMAT_ID_MP4_KARAOKE]
    FORMAT_IDS_DATASOURCE_INTERVIEW = [FORMAT_ID_MP4_INTERVIEW]
    FORMAT_IDS_DATASOURCE_BACKSTAGE = [FORMAT_ID_MP4_BACKSTAGE]
    FORMAT_IDS_DATASOURCE_TV_SPOT = [FORMAT_ID_MP4_TV_SPOT]
    FORMAT_IDS_DATASOURCE_TUTORIAL = [FORMAT_ID_MP4_TUTORIAL]

    FORMAT_IDS_SINGLE_OFFICIAL = [FORMAT_ID_MP4_FULL, FORMAT_ID_MP3_FULL]
    KEY_SINGLE_OFFICIAL = "SINGLE_OFFICIAL"

    FORMAT_IDS_SINGLE_QUALIFIED = [FORMAT_ID_MP4_FULL, FORMAT_ID_MP4_STATIC]

    FORMAT_IDS_SINGLE_FEATURE_REMIX = [FORMAT_ID_MP4_FEATURE, FORMAT_ID_MP3_FEATURE, FORMAT_ID_MP4_REMIX]
    KEY_SINGLE_FEATURE_REMIX = "SINGLE_FEATURE_REMIX"

    FORMAT_IDS_SINGLE_LIVE = [FORMAT_ID_MP4_LIVE, FORMAT_ID_MP3_LIVE]
    KEY_SINGLE_LIVE = "SINGLE_LIVE"

    FORMAT_IDS_SINGLE_FEATURE = [FORMAT_ID_MP4_FEATURE, FORMAT_ID_MP3_FEATURE]
    KEY_SINGLE_FEATURE = "SINGLE_FEATURE"

    FORMAT_IDS_SINGLE_REMIX = [FORMAT_ID_MP4_REMIX]
    KEY_SINGLE_REMIX = "SINGLE_REMIX"

    FORMAT_IDS_SINGLE_COVER = [FORMAT_ID_MP4_COVER, FORMAT_ID_MP3_COVER]
    KEY_SINGLE_COVER = "SINGLE_COVER"

    FORMAT_IDS_SINGLE_TRACK_LIST = [FORMAT_ID_MP4_FULL, FORMAT_ID_MP3_FULL, FORMAT_ID_MP4_LIVE, FORMAT_ID_MP3_LIVE]
    KEY_SINGLE_TRACK_LIST = "SINGLE_TRACK_LIST"

    FORMAT_IDS_SINGLE_OFFICIAL_VIDEO = [FORMAT_ID_MP4_FULL]
    KEY_SINGLE_OFFICIAL_VIDEO = "SINGLE_OFFICIAL_VIDEO"

    FORMAT_IDS_SINGLE_OFFICIAL_AUDIO = [FORMAT_ID_MP3_FULL]
    KEY_SINGLE_OFFICIAL_AUDIO = "SINGLE_OFFICIAL_AUDIO"

    FORMAT_IDS_SINGLE_FAN_CAM = [FORMAT_ID_MP4_FAN_CAM]
    KEY_SINGLE_FAN_CAM = "SINGLE_FAN_CAM"

    FORMAT_IDS_SINGLE_LYRIC = [FORMAT_ID_MP4_LYRIC]
    KEY_SINGLE_LYRIC = "SINGLE_LYRIC"

    FORMAT_IDS_SINGLE_UNPLUGGED = [FORMAT_ID_MP4_UNPLUGGED]
    KEY_SINGLE_UNPLUGGED = "SINGLE_UNPLUGGED"

    FORMAT_IDS_SINGLE_MASHUP = [FORMAT_ID_MP4_MASHUP]
    KEY_SINGLE_MASHUP = "SINGLE_MASHUP"

    FORMAT_IDS_SINGLE_DANCE = [FORMAT_ID_MP4_DANCE]
    KEY_SINGLE_DANCE = "SINGLE_DANCE"

    FORMAT_IDS_SINGLE_TOUR = [FORMAT_ID_MP4_TOUR]
    KEY_SINGLE_TOUR = "SINGLE_TOUR"

    FORMAT_IDS_SINGLE_360_VR = [FORMAT_ID_MP4_360_VR]
    KEY_SINGLE_360_VR = "SINGLE_360_VR"

    FORMAT_IDS_SINGLE_INSTRUMENTAL = [FORMAT_ID_MP4_INSTRUMENTAL]
    KEY_SINGLE_INSTRUMENTAL = "SINGLE_INSTRUMENTAL"

    FORMAT_IDS_SINGLE_KARAOKE = [FORMAT_ID_MP4_KARAOKE]
    KEY_SINGLE_KARAOKE = "SINGLE_KARAOKE"

    FORMAT_IDS_SINGLE_INTERVIEW = [FORMAT_ID_MP4_INTERVIEW]
    KEY_SINGLE_INTERVIEW = "SINGLE_INTERVIEW"

    FORMAT_IDS_SINGLE_BACKSTAGE = [FORMAT_ID_MP4_BACKSTAGE]
    KEY_SINGLE_BACKSTAGE = "SINGLE_BACKSTAGE"

    FORMAT_IDS_SINGLE_TV_SPOT = [FORMAT_ID_MP4_TV_SPOT]
    KEY_SINGLE_TV_SPOT = "SINGLE_TV_SPOT"

    FORMAT_IDS_SINGLE_TUTORIAL = [FORMAT_ID_MP4_TUTORIAL]
    KEY_SINGLE_TUTORIAL = "SINGLE_TUTORIAL"

    FORMAT_IDS_SINGLE_ALL = FORMAT_IDS_SINGLE_OFFICIAL_VIDEO + FORMAT_IDS_SINGLE_OFFICIAL_AUDIO \
                            + FORMAT_IDS_SINGLE_LIVE + FORMAT_IDS_SINGLE_FEATURE + FORMAT_IDS_SINGLE_REMIX + FORMAT_IDS_SINGLE_LYRIC \
                            + FORMAT_IDS_SINGLE_COVER

    SINGLE_FORMATS = {
        KEY_SINGLE_OFFICIAL: FORMAT_IDS_SINGLE_OFFICIAL,
        KEY_SINGLE_LIVE: FORMAT_IDS_SINGLE_LIVE,
        KEY_SINGLE_FEATURE: FORMAT_IDS_SINGLE_FEATURE,
        KEY_SINGLE_REMIX: FORMAT_IDS_SINGLE_REMIX,
        KEY_SINGLE_COVER: FORMAT_IDS_SINGLE_COVER,
        KEY_SINGLE_OFFICIAL_VIDEO: FORMAT_IDS_SINGLE_OFFICIAL_VIDEO,
        KEY_SINGLE_OFFICIAL_AUDIO: FORMAT_IDS_SINGLE_OFFICIAL_AUDIO,
        KEY_SINGLE_TRACK_LIST: FORMAT_IDS_SINGLE_TRACK_LIST,
        KEY_SINGLE_FAN_CAM: FORMAT_IDS_SINGLE_FAN_CAM,
        KEY_SINGLE_LYRIC: FORMAT_IDS_SINGLE_LYRIC,
        KEY_SINGLE_UNPLUGGED: FORMAT_IDS_SINGLE_UNPLUGGED,
        KEY_SINGLE_MASHUP: FORMAT_IDS_SINGLE_MASHUP,
        KEY_SINGLE_DANCE: FORMAT_IDS_SINGLE_DANCE,
        KEY_SINGLE_TOUR: FORMAT_IDS_SINGLE_TOUR,
        KEY_SINGLE_360_VR: FORMAT_IDS_SINGLE_360_VR,
        KEY_SINGLE_INSTRUMENTAL: FORMAT_IDS_SINGLE_INSTRUMENTAL,
        KEY_SINGLE_KARAOKE: FORMAT_IDS_SINGLE_KARAOKE,
        KEY_SINGLE_INTERVIEW: FORMAT_IDS_SINGLE_INTERVIEW,
        KEY_SINGLE_BACKSTAGE: FORMAT_IDS_SINGLE_BACKSTAGE,
        KEY_SINGLE_TV_SPOT: FORMAT_IDS_SINGLE_TV_SPOT,
        KEY_SINGLE_TUTORIAL: FORMAT_IDS_SINGLE_TUTORIAL
    }

    FORMAT_IDS_ARTIST_OFFICIAL = [FORMAT_ID_MP4_FULL]
    KEY_ARTIST_OFFICIAL = "ARTIST_OFFICIAL"

    FORMAT_IDS_ARTIST_AUDIO = [FORMAT_ID_MP3_FULL]
    KEY_ARTIST_AUDIO = "ARTIST_AUDIO"

    FORMAT_IDS_ARTIST_LIVE = [FORMAT_ID_MP4_LIVE, FORMAT_ID_MP3_LIVE]
    KEY_ARTIST_LIVE = "ARTIST_LIVE"

    FORMAT_IDS_ARTIST_FEATURE = [FORMAT_ID_MP4_FEATURE, FORMAT_ID_MP3_FEATURE]
    KEY_ARTIST_FEATURE = "ARTIST_FEATURE"

    FORMAT_IDS_ARTIST_REMIX = [FORMAT_ID_MP4_REMIX]
    KEY_ARTIST_REMIX = "ARTIST_REMIX"

    FORMAT_IDS_ARTIST_COVER = [FORMAT_ID_MP4_COVER, FORMAT_ID_MP3_COVER]
    KEY_ARTIST_COVER = "ARTIST_COVER"

    FORMAT_IDS_ARTIST_FAN_CAM = [FORMAT_ID_MP4_FAN_CAM]
    KEY_ARTIST_FAN_CAM = "ARTIST_FAN_CAM"

    FORMAT_IDS_ARTIST_LYRIC = [FORMAT_ID_MP4_LYRIC]
    KEY_ARTIST_LYRIC = "ARTIST_LYRIC"

    FORMAT_IDS_ARTIST_UNPLUGGED = [FORMAT_ID_MP4_UNPLUGGED]
    KEY_ARTIST_UNPLUGGED = "ARTIST_UNPLUGGED"

    FORMAT_IDS_ARTIST_MASHUP = [FORMAT_ID_MP4_MASHUP]
    KEY_ARTIST_MASHUP = "ARTIST_MASHUP"

    FORMAT_IDS_ARTIST_DANCE = [FORMAT_ID_MP4_DANCE]
    KEY_ARTIST_DANCE = "ARTIST_DANCE"

    FORMAT_IDS_ARTIST_TOUR = [FORMAT_ID_MP4_TOUR]
    KEY_ARTIST_TOUR = "ARTIST_TOUR"

    FORMAT_IDS_ARTIST_360_VR = [FORMAT_ID_MP4_360_VR]
    KEY_ARTIST_360_VR = "ARTIST_360_VR"

    FORMAT_IDS_ARTIST_INSTRUMENTAL = [FORMAT_ID_MP4_INSTRUMENTAL]
    KEY_ARTIST_INSTRUMENTAL = "ARTIST_INSTRUMENTAL"

    FORMAT_IDS_ARTIST_KARAOKE = [FORMAT_ID_MP4_KARAOKE]
    KEY_ARTIST_KARAOKE = "ARTIST_KARAOKE"

    FORMAT_IDS_ARTIST_INTERVIEW = [FORMAT_ID_MP4_INTERVIEW]
    KEY_ARTIST_INTERVIEW = "ARTIST_INTERVIEW"

    FORMAT_IDS_ARTIST_BACKSTAGE = [FORMAT_ID_MP4_BACKSTAGE]
    KEY_ARTIST_BACKSTAGE = "ARTIST_BACKSTAGE"

    FORMAT_IDS_ARTIST_TV_SPOT = [FORMAT_ID_MP4_TV_SPOT]
    KEY_ARTIST_TV_SPOT = "ARTIST_TV_SPOT"

    FORMAT_IDS_ARTIST_TUTORIAL = [FORMAT_ID_MP4_TUTORIAL]
    KEY_ARTIST_TUTORIAL = "ARTIST_TUTORIAL"

    FORMAT_IDS_ARTIST_MAIN = FORMAT_IDS_ARTIST_OFFICIAL + FORMAT_IDS_ARTIST_AUDIO + FORMAT_IDS_ARTIST_LIVE \
                             + FORMAT_IDS_ARTIST_FEATURE + FORMAT_IDS_ARTIST_REMIX + FORMAT_IDS_ARTIST_COVER + FORMAT_IDS_ARTIST_FAN_CAM \
                             + FORMAT_IDS_ARTIST_LYRIC + FORMAT_IDS_ARTIST_UNPLUGGED + FORMAT_IDS_ARTIST_MASHUP + FORMAT_IDS_ARTIST_DANCE \
                             + FORMAT_IDS_ARTIST_INSTRUMENTAL + FORMAT_IDS_ARTIST_KARAOKE + FORMAT_IDS_ARTIST_TUTORIAL

    FORMAT_IDS_ARTIST_CONTENT = FORMAT_IDS_ARTIST_360_VR + FORMAT_IDS_ARTIST_TV_SPOT + FORMAT_IDS_ARTIST_BACKSTAGE \
                                + FORMAT_IDS_ARTIST_INTERVIEW + FORMAT_IDS_ARTIST_TOUR

    KEY_ARTIST_TOTAL = "ARTIST_TOTAL"

    ARTIST_FORMATS = {
        KEY_ARTIST_OFFICIAL: FORMAT_IDS_ARTIST_OFFICIAL,
        KEY_ARTIST_AUDIO: FORMAT_IDS_ARTIST_AUDIO,
        KEY_ARTIST_LIVE: FORMAT_IDS_ARTIST_LIVE,
        KEY_ARTIST_FEATURE: FORMAT_IDS_ARTIST_FEATURE,
        KEY_ARTIST_REMIX: FORMAT_IDS_ARTIST_REMIX,
        KEY_ARTIST_COVER: FORMAT_IDS_ARTIST_COVER,
        KEY_ARTIST_FAN_CAM: FORMAT_IDS_ARTIST_FAN_CAM,
        KEY_ARTIST_LYRIC: FORMAT_IDS_ARTIST_LYRIC,
        KEY_ARTIST_UNPLUGGED: FORMAT_IDS_ARTIST_UNPLUGGED,
        KEY_ARTIST_MASHUP: FORMAT_IDS_ARTIST_MASHUP,
        KEY_ARTIST_DANCE: FORMAT_IDS_ARTIST_DANCE,
        KEY_ARTIST_INSTRUMENTAL: FORMAT_IDS_ARTIST_INSTRUMENTAL,
        KEY_ARTIST_KARAOKE: FORMAT_IDS_ARTIST_KARAOKE,
        KEY_ARTIST_TUTORIAL: FORMAT_IDS_ARTIST_TUTORIAL
    }

    ARTIST_CONTENT_FORMATS = {
        KEY_ARTIST_360_VR: FORMAT_IDS_ARTIST_360_VR,
        KEY_ARTIST_TV_SPOT: FORMAT_IDS_ARTIST_TV_SPOT,
        KEY_ARTIST_BACKSTAGE: FORMAT_IDS_ARTIST_BACKSTAGE,
        KEY_ARTIST_INTERVIEW: FORMAT_IDS_ARTIST_INTERVIEW,
        KEY_ARTIST_TOUR: FORMAT_IDS_ARTIST_TOUR
    }

    FORMAT_IDS_ARTIST_TRACK_LIST = [FORMAT_ID_MP4_FULL, FORMAT_ID_MP3_FULL]
    KEY_ARTIST_TRACK_LIST = "ARTIST_TRACK_LIST"

    FORMAT_IDS_ALBUM_OFFICIAL = [FORMAT_ID_MP4_FULL, FORMAT_ID_MP3_FULL]
    KEY_ALBUM_OFFICIAL = "ALBUM_OFFICIAL"

    FORMAT_IDS_ALBUM_OFFICIAL_VIDEO = [FORMAT_ID_MP4_FULL]
    KEY_ALBUM_OFFICIAL_VIDEO = "ALBUM_OFFICIAL_VIDEO"

    FORMAT_IDS_ALBUM_STATIC_VIDEO = [FORMAT_ID_MP3_FULL]
    KEY_ALBUM_STATIC_VIDEO = "ALBUM_STATIC_VIDEO"

    FORMAT_IDS_ALBUM_LIVE = [FORMAT_ID_MP4_LIVE, FORMAT_ID_MP3_LIVE]
    KEY_ALBUM_LIVE = "ALBUM_LIVE"

    FORMAT_IDS_ALBUM_FEATURE = [FORMAT_ID_MP4_FEATURE, FORMAT_ID_MP3_FEATURE]
    KEY_ALBUM_FEATURE = "ALBUM_FEATURE"

    FORMAT_IDS_ALBUM_REMIX = [FORMAT_ID_MP4_REMIX]
    KEY_ALBUM_REMIX = "ALBUM_REMIX"

    FORMAT_IDS_ALBUM_FAN_CAM = [FORMAT_ID_MP4_FAN_CAM]
    KEY_ALBUM_FAN_CAM = "ALBUM_FAN_CAM"

    FORMAT_IDS_ALBUM_COVER = [FORMAT_ID_MP4_COVER, FORMAT_ID_MP3_COVER]
    KEY_ALBUM_COVER = "ALBUM_COVER"

    FORMAT_IDS_ALBUM_LYRIC = [FORMAT_ID_MP4_LYRIC]
    KEY_ALBUM_LYRIC = "ALBUM_LYRIC"

    FORMAT_IDS_ALBUM_UNPLUGGED = [FORMAT_ID_MP4_UNPLUGGED]
    KEY_ALBUM_UNPLUGGED = "ALBUM_UNPLUGGED"

    FORMAT_IDS_ALBUM_MASHUP = [FORMAT_ID_MP4_MASHUP]
    KEY_ALBUM_MASHUP = "ALBUM_MASHUP"

    FORMAT_IDS_ALBUM_DANCE = [FORMAT_ID_MP4_DANCE]
    KEY_ALBUM_DANCE = "ALBUM_DANCE"

    FORMAT_IDS_ALBUM_TOUR = [FORMAT_ID_MP4_TOUR]
    KEY_ALBUM_TOUR = "ALBUM_TOUR"

    FORMAT_IDS_ALBUM_360_VR = [FORMAT_ID_MP4_360_VR]
    KEY_ALBUM_360_VR = "ALBUM_360_VR"

    FORMAT_IDS_ALBUM_INSTRUMENTAL = [FORMAT_ID_MP4_INSTRUMENTAL]
    KEY_ALBUM_INSTRUMENTAL = "ALBUM_INSTRUMENTAL"

    FORMAT_IDS_ALBUM_KARAOKE = [FORMAT_ID_MP4_KARAOKE]
    KEY_ALBUM_KARAOKE = "ALBUM_KARAOKE"

    FORMAT_IDS_ALBUM_INTERVIEW = [FORMAT_ID_MP4_INTERVIEW]
    KEY_ALBUM_INTERVIEW = "ALBUM_INTERVIEW"

    FORMAT_IDS_ALBUM_BACKSTAGE = [FORMAT_ID_MP4_BACKSTAGE]
    KEY_ALBUM_BACKSTAGE = "ALBUM_BACKSTAGE"

    FORMAT_IDS_ALBUM_TV_SPOT = [FORMAT_ID_MP4_TV_SPOT]
    KEY_ALBUM_TV_SPOT = "ALBUM_TV_SPOT"

    FORMAT_IDS_ALBUM_TUTORIAL = [FORMAT_ID_MP4_TUTORIAL]
    KEY_ALBUM_TUTORIAL = "ALBUM_TUTORIAL"

    FORMAT_IDS_ALBUM_MAIN = FORMAT_IDS_ALBUM_OFFICIAL_VIDEO + FORMAT_IDS_ALBUM_STATIC_VIDEO \
                            + FORMAT_IDS_ALBUM_LIVE + FORMAT_IDS_ALBUM_REMIX + FORMAT_IDS_ALBUM_FEATURE

    KEY_ALBUM_TOTAL = "ALBUM_TOTAL"
    KEY_ALBUM_TRACK_LIST = "ALBUM_TRACK_LIST"
    KEY_ALBUM_FULL_TRACK = "ALBUM_FULL_TRACK"

    ALBUM_FORMATS = {
        KEY_ALBUM_OFFICIAL_VIDEO: FORMAT_IDS_ALBUM_OFFICIAL_VIDEO,
        KEY_ALBUM_STATIC_VIDEO: FORMAT_IDS_ALBUM_STATIC_VIDEO,
        KEY_ALBUM_OFFICIAL: FORMAT_IDS_ALBUM_OFFICIAL,
        KEY_ALBUM_LIVE: FORMAT_IDS_ALBUM_LIVE,
        KEY_ALBUM_FEATURE: FORMAT_IDS_ALBUM_FEATURE,
        KEY_ALBUM_REMIX: FORMAT_IDS_ALBUM_REMIX,
        KEY_ALBUM_FAN_CAM: FORMAT_IDS_ALBUM_FAN_CAM,
        KEY_ALBUM_COVER: FORMAT_IDS_ALBUM_COVER,
        KEY_ALBUM_LYRIC: FORMAT_IDS_ALBUM_LYRIC,
        KEY_ALBUM_UNPLUGGED: FORMAT_IDS_ALBUM_UNPLUGGED,
        KEY_ALBUM_MASHUP: FORMAT_IDS_ALBUM_MASHUP,
        KEY_ALBUM_DANCE: FORMAT_IDS_ALBUM_DANCE,
        KEY_ALBUM_TOUR: FORMAT_IDS_ALBUM_TOUR,
        KEY_ALBUM_360_VR: FORMAT_IDS_ALBUM_360_VR,
        KEY_ALBUM_INSTRUMENTAL: FORMAT_IDS_ALBUM_INSTRUMENTAL,
        KEY_ALBUM_KARAOKE: FORMAT_IDS_ALBUM_KARAOKE,
        KEY_ALBUM_INTERVIEW: FORMAT_IDS_ALBUM_INTERVIEW,
        KEY_ALBUM_BACKSTAGE: FORMAT_IDS_ALBUM_BACKSTAGE,
        KEY_ALBUM_TV_SPOT: FORMAT_IDS_ALBUM_TV_SPOT,
        KEY_ALBUM_TUTORIAL: FORMAT_IDS_ALBUM_TUTORIAL
    }

    KEY_THEME_TRACK_LIST = "THEME_TRACK_LIST"

    FORMAT_ID_NONE = ""

    PRIORITY_MAX = 99999
